"""
generator.py

Generates a professional Due Diligence Report
in Microsoft Word (.docx) format.
"""

import os
from datetime import datetime

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

REPORT_FOLDER = "reports/generated_reports"

os.makedirs(REPORT_FOLDER, exist_ok=True)


def generate_report(report_text: str):
    """
    Generate a Due Diligence Report.

    Args:
        report_text (str)

    Returns:
        Path of generated report
    """

    document = Document()

    # ----------------------------
    # Title
    # ----------------------------
    title = document.add_heading(
        "AI Due Diligence Report",
        level=1
    )

    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    # ----------------------------
    # Timestamp
    # ----------------------------
    timestamp = document.add_paragraph()

    timestamp.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    timestamp.add_run(
        f"Generated on: {datetime.now().strftime('%d %B %Y %I:%M %p')}"
    ).italic = True

    document.add_paragraph()

    # ----------------------------
    # Executive Summary
    # ----------------------------
    heading = document.add_heading(
        "Analysis",
        level=2
    )

    heading.style.font.size = Pt(16)

    paragraph = document.add_paragraph()

    paragraph.style.font.size = Pt(11)

    paragraph.add_run(report_text)

    document.add_page_break()

    # ----------------------------
    # Footer
    # ----------------------------
    footer = document.sections[0].footer

    footer_para = footer.paragraphs[0]

    footer_para.text = (
        "Generated by AI Due Diligence Copilot"
    )

    # ----------------------------
    # Save Report
    # ----------------------------
    filename = (
        f"Due_Diligence_Report_"
        f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    )

    filepath = os.path.join(
        REPORT_FOLDER,
        filename
    )

    document.save(filepath)

    return filepath


if __name__ == "__main__":

    sample = """
Executive Summary

The company demonstrates stable revenue growth
with moderate operational risks.

Financial Analysis

Revenue has increased steadily.

Business Analysis

Strong customer retention.

Operational Risks

Supplier dependency.

Recommendation

Hold.
"""

    path = generate_report(sample)

    print("Report saved at:")

    print(path)